### ISSUE TITLE
[Extension] Offer to add to sidekick when on github.com

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick#115]
Proposed flow:
- go to https://github.com/${owner}/${repo}
- click the sidekick extension button
- if the project is not a known project, offer to add it to the config

This could work also for branches, i.e. if you are on https://github.com/${owner}/${repo}/tree/${branch}.

This would be an easy way to add a new sidekick config.

**Comment by rofe** [comment]
If a project has already been added, the context menu item will be grayed out and show a checkmark:
![image](https://user-images.githubusercontent.com/1609742/139668650-3a528a27-dbe9-4eb4-b86e-5aa9b45fc916.png)
