### ISSUE TITLE
Support shared secret for Admin API

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick#124]
See https://github.com/adobe/helix-admin/issues/282
> for some projects a shared secret based auth may be a good way to allow and revoke access to the admin API for a project via a shared secret that is sent from sidekick et al.

**Comment by tripodsan** [comment]
new requirements:
- the shared secrets have a `name` and `secrets` part (eg: username, password)
- the user should be able to enter either the tuple (name, password) or it's base64 encoded form: (`base64(name:password)`)
- the sidekick should store it in `base64` encoded form which it also uses for the basic auth
- sharing the sidekick config should also use the `base64` encoded form

**Comment by rofe** [comment]
> the user should be able to enter either the user name and password or as tuple

I think it would feel more natural to just have separate username and password fields, and have the extension stitch the tuple together.

**Comment by rofe** [comment]
https://github.com/adobe/helix-admin/issues/282 has been resolved as won't fix, so same here.
