### ISSUE TITLE
[BUG] Sidekick with a reference to a repo with Uppercase letters does not display any actions on preview page

### ISSUE THREAD

**Issue by LucaNerlich** [adobe/helix-sidekick#137]
**Description**
Sidekick Actions do not work, when referencing a repo / owner with uppercase letters, such as myself.

Sidekick Share: `https://www.hlx.live/tools/sidekick/?project=&from=&giturl=https%3A%2F%2Fgithub.com%2FLucaNerlich%2Fhelix-tutorial%2Ftree%2Fmain&hlx3=true`

**To Reproduce**
1. Go to 'https://www.hlx.live/tools/sidekick'
2. Enter repo url `https://github.com/LucaNerlich/helix-tutorial` and generate sidekick.
3. Use generated booklet on preview page
4. Observe that no actions are being loaded.

**Expected behavior**
Sidekick opens and displays the following actions

![image](https://user-images.githubusercontent.com/5942270/141097097-5957e9fb-8660-45d1-9134-38750d126e02.png)

**Version:**
v14.0.6

**Comment by rofe** [comment]
Fixed in Admin API
