### ISSUE TITLE
Load config and plugins from project host

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick#14]
The sidekick config is currently stored in the author's bookmarklet URL. When an update to the config is required, e.g. to make use of a new feature, authors are asked to update their bookmarklets (i.e. replace it with a new one). Even though the sidekick redirects them to the right URL to get the fresh bookmarklet, it is still a manual task.

The sidekick also makes a request to the project host to see if there are any custom plugins to load.

In order to avoid manual bookmarklet updates in the future, both the sidekick config and plugins could be loaded from a single config file located on the project host.

**Comment by tripodsan** [comment]
>  file located on the project host.

i.e. github delivered through helix? eg: https://main--repo-owner.hlx.page/helix-sidekick.json ?

**Comment by rofe** [comment]
I was thinking more of a JS file e.g. `https://main--repo-owner.hlx.page/tools/sidekick/config.js` so customers can specify listeners for custom buttons.

Example:
```js
// window.hlx.initSidekick(config) is provided by the sidekick app.js loaded prior to this file
window.hlx.initSidekick({
  project: 'Test Project',
  host: 'www.foo.bar',
  hlx3: true,
  byocdn: true,
  plugins: [
    {
      id: 'test',
      button: {
        text: 'Test',
        action: (evt) => {
          console.log('test');
        },
      },
    },
  ],
});
```
