### ISSUE TITLE
Strange character over share button when viewing a script with sidekick active

### ISSUE THREAD

**Issue by dylandepass** [adobe/helix-sidekick#143]
Had the sidekick open when looking at the script below and noticed this weird character over the share button. Not sure if it's related to the repo not having a `tools/sidekick/config.js` in the repo.

https://sko--dc-forms--adobe.hlx.live/dfl/dfl-forms.bundle.js

Not a huge deal but thought you may want to know if you haven't seen it before.

![Screen Shot 2021-11-16 at 2 05 41 PM](https://user-images.githubusercontent.com/3231084/142049737-0023334b-58f4-4807-8511-c3ed9a562c19.png)

P.S LOVING the extension ;)

**Comment by rofe** [comment]
Yeah, the current share icon is a bit of a hack 😄 - it is made up of several characters, one of them being a unicode dot which seems to be unavailable in this particular view. I think the proper fix would be to use a real SVG icon here...

**Comment by rofe** [comment]
This should be fixed now.
