### ISSUE TITLE
JSON previews

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-sidekick#193]
generally for an author the JSON preview, is probably largely useless, so it would be great if the sidekick could point to something in `/tools/` or possibly even more built-in by default that would display the table oriented content somewhat more user friendly.
ideally this would also serve as an extension point where someone could register a path glob or a filename to trigger a special preview... i imagine something like `/tools/table-viewers/redirect.html?src=/redirects.json`

**Comment by rofe** [comment]
Great idea! but instead of loading an entirely different page, I think it would be better to allow projects to specify the code for the special view in `config.js`, e.g.
```js
  specialViews: [
    {
      path: '/en/**.json',
      js: (container, content) => {
        const { limit, total } = JSON.parse(content);
        container.textContent = `Custom data view - Showing ${limit} of ${total} records`;
      },
      css: '.hlx-sk-special-view { color: orange }',
    },
  ],
```
