### ISSUE TITLE
[JSON Preview] Support for multiple sheets 

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick#219]
If the xlsx file has multiple sheets, the JSON Preview shows a black screen. I assume it is looking for a Helix default.

Example: https://main--blog--adobe.hlx3.page/en/drafts/alex/bulkoperationsconfig.json

Ideally, each sheet should be in separate tab and user can switch between the tabs.

cc @rofe

**Comment by rofe** [comment]
No, but it is looking for a `data` array at the root... I'll check for the `:type="multisheet"` property
