### ISSUE TITLE
publish button does not work with hlx3

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-sidekick#28]
Do the full setup of a site running with hlx3.
Go to page preview and hit the publish button, you are redirected to a 404 page.

Reason: the `main` branch name is missing in the URL.

cc @rofe

**Comment by rofe** [comment]
Can you confirm that the publish action worked, and it's just redirecting to the "wrong" URL afterwards?

**Comment by kptdobe** [comment]
The admin action post to /live responds 200 but the page is not up-to-date (if I update manually the url and add the branch name)

**Comment by rofe** [comment]
Ok, and when you `curl -X PURGE` it?

**Comment by rofe** [comment]
Looks like you were ahead of your time and using hlx3 before all the moving parts had a time to catch up 😉 

I would suggest to use the following workaround:
1. add a `/tools/sidekick/plugins.js` to your project
2. add `window.hlx.sidekick.config.outerHost = 'main--repo--owner.hlx.live';` to it

This will fix the broken redirect until the sidekick provides the fix - and should continue to work after that.

**Comment by rofe** [comment]
Should be fixed with #29.
