### ISSUE TITLE
Enable sidekick publish on files in `.helix/`

### ISSUE THREAD

**Issue by dylandepass** [adobe/helix-sidekick#306]
As part of the [content-bus config merge](https://github.com/adobe/helix-admin/pull/604) users will need to be able to publish the `.helix/headers.json` file. 

Files contained in `.helix/` will continue to be blocked from being served via the pipeline but the preview/publish operations in admin will trigger a merge of all config files into `.helix/confilg-all.json` and `/helix-env.json`. Where the latter does not contain any sensitive data from `.helix/config.json` and can be used by other helix systems (besides pipeline) to extract the production host.

**Comment by rofe** [comment]
So basically, only `.helix/config.json` should be treated as a special case?

cc @tripodsan

**Comment by tripodsan** [comment]
> So basically, only `.helix/config.json` should be treated as a special case?
> 
> cc @tripodsan

for now, I would just disable publish on all `/.helix`. we can still open it up if needed.

**Comment by rofe** [comment]
OK, that's the current status. Then I don't understand this enhancement request. 😄

**Comment by tripodsan** [comment]
right, I forgot that there is no `publish` button on the edit urls. closing as won't fix.

**Comment by dylandepass** [comment]
Sorry, somehow missed this convo..

`.helix/config-all.json`  is unique to each partition as per.
https://github.com/adobe/helix-html-pipeline/blob/main/src/steps/fetch-config-all.js#L103

If we are not going to enable publish we should do something similar to what is done with preview operations on `.helix/config` where somehow (haven't looked) a preview results in `.helix/config-all.json` in the `live` partition being updated.

Do you agree @tripodsan?

**Comment by tripodsan** [comment]
I think `/.helix/headers.json` should also not need a publish.
