### ISSUE TITLE
`[Live]` button doesn't show up if config doesn't have a `host` property.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-sidekick#53]
**Description**
in the business-website repository, the config didn't have a `host` property,
and then the `Live` button is missing:

![image](https://user-images.githubusercontent.com/917628/127630865-b3cb5df1-6a22-42c9-b0f6-2cffe4dfa6d5.png)

### workaround

execute the following in your console:

```
hlx.sidekickConfig.host='www.adobe.com'; hlx.initSidekick(); delete hlx.sidekick; hlx.initSidekick()
```

**Comment by rofe** [comment]
For legacy Helix projects, this is by design, because the sidekick couldn't just presume that an outer CDN had been set up. But with Helix 3, we always have a `*.hlx.live` site available, so the sidekick could show the _Live_ as well as the _Publish_ button even if `host` is missing.
