### ISSUE TITLE
"Personalize" Button for Adobe Audience Manager

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-sidekick#64]
In the context of https://github.com/adobe/express-website-issues/issues/158 we should add a "Personalize" button to the Sidekick, which will work like this:

<img width="1275" alt="Screen Shot 2021-08-18 at 13 22 13" src="https://user-images.githubusercontent.com/39613/129889642-ab12a4aa-0fd5-469f-9e20-b6c5e39a69c0.png">

## Preview/Live/Production

Clicking the button will open a dropdown that allows the user to select or reset an audience. The list of audiences is pulled from `/_audiences.json` at the site root, which is populated by a table consisting of the columns:
- name: display name of the audience, e.g. "returning visitor"
- description: optional description of the audience, shown as tooltip, e.g. "visitors who have been to adobe.com before in the last two weeks"
- id: ID of the audience manager audience, e.g. 1738236

Upon selecting an audience, the button will:
- set the `window.hlx.audience` variable to the selected ID
- fire a `window.dispatchEvent(new CustomEvent('helix-audiencechanged', { detail: audienceId }));` event
- persist the selected audience in a cookie or session storage

An (upcoming) personalization component will be able to listen to these events or read the values and display the matching content.

## Edit

The same dropdown will be shown, but without an option to clear or set the audience, instead clicking an audience name will copy the audience ID so that it can be used in the first column of the personalization block's table

## Edit 2

Incorporated @rofe's suggestions from below: https://github.com/adobe/helix-sidekick/issues/64#issuecomment-903138777

**Comment by rofe** [comment]
@trieloff A few suggested changes:

> - set the `window.helix.audience` variable to the selected ID

I would (re)use `window.hlx` object for this which is already being used by the Sidekick. On the other hand, do we really need this variable if the selected audience is also broadcast via event and stored in `localStorage`?

> - fire a `window.helix.on('audiencechanged')` event

I would propose to fire the event on the `window` instead, as listening to an event on an object that may or may not exist (before the Sidekick is initialized, `window.hlx` yet would be cumbersome:
```js
window.dispatchEvent(new Event('helix-audiencechanged`, { detail: audienceId }));
```
Then blocks can register listeners like this:
```js
window.addEventListener('helix-audiencechanged', (evt) => console.log(evt.detail);
```

And a few questions:
1. Who is the persona authoring the `_audiences` sheet, and where would they get the correct IDs from?
2. In the production (i.e. non-simulation) scenario, where would the event be fired and the audience ID be stored in `localStorage`? I imagine we'd need a few helper functions to trigger this in a project's `martech.js` based on real data from EC...

cc @davidnuescheler

**Comment by trieloff** [comment]
> Who is the persona authoring the _audiences sheet, and where would they get the correct IDs from?

The same person that defines audiences in AudienceManager. They get it from the AudienceManager UI.

> In the production (i.e. non-simulation) scenario, where would the event be fired and the audience ID be stored in localStorage? I imagine we'd need a few helper functions to trigger this in a project's martech.js based on real data from EC...
> On the other hand, do we really need this variable if the selected audience is also broadcast via event and stored in localStorage?

Oddly enough, this is the same question, asked twice.

The `window.hlx.audience` variable + `helix-audiencechanged` event shall be the main interface to use when building a compontent that interacts with audiences or uses targeting. The value will be populated from two sources:

1. the AudienceManager JSON API (by using the Experience Cloud ID Cookie) 
2. the Cookie/LocalStorage/Sidekick UI

(2) overrides (1), so that a user with the sidekick can select audiences at any time.

**Comment by rofe** [comment]
> Oddly enough, this is the same question, asked twice.

Sorry 😄 

I figured we'd need some sot of "connecive tissue" between Audience Manager running on a page and blocks using personalization, to make sure that `window.hlx.audience` is set and/or the `helix-audiencechanged` event gets fired...
