### ISSUE TITLE
Delete and Unpublish

### ISSUE THREAD

**Issue by rofe** [adobe/helix-sidekick#76]
If a page no longer has a source document, it should be possible for authors to remove its renditions in preview and live (effectively unpublishing it).

If a missing source document is detected in..
- Preview: _Reload_ and _Publish_ plugins should be hidden, _Delete_ plugin should be shown
- Live: _Publish_ should be hidden,  _Delete_ plugin should be shown

When clicked and confirmed by the user, all renditions will be removed.

**Comment by kptdobe** [comment]
I would say we also need the capability to unpublish a page which has been accidentally published and should not be available yet.

**Comment by rofe** [comment]
@kptdobe right, so maybe we need 2 distinct plugins:
- Preview: _Delete_  deletes the resource from both preview and live buckets, then redirects to the homepage
- Live: _Unpublish_ deletes the resource from the live bucket only, then redirects to the preview page

wdyt?

**Comment by kptdobe** [comment]
Technically yes, but not sure how the end-user would understand that.
As a user, you do not really care about the file still being stored in the preview bucket.
Thinking about use cases, I only see 2: 
1. end-user sees an article on the production website that has nothing todo here yet, you want to un-publish it.
2. end-user deletes the source file and probably expects the page to disappear from the site.

**Comment by rofe** [comment]
> 1. end-user sees an article on the production website that has nothing todo here yet, you want to un-publish it.

Yes. The sidekick should offer an _Unpublish_ action if it detects that the page is published (i.e. in the live bucket)

> 2. end-user deletes the source file and probably expects the page to disappear from the site.

Yes in theory, however in reality, we can't hook into the "backend UI" (SP, gDrive) to warn the user of the consequences of deleting/moving a source document. Such could also be an accident, and the end-user may later notice their mistake and restore the document from the trash. So we shouldn't auto-delete anything in the preview and live buckets based on such an event, but instead give the end-user the ability to clean up manually. 

Evolved from https://github.com/adobe/helix-sidekick/issues/76#issuecomment-919861286:
- All environments:
   - Hide _Edit_ if there is no source document
   - Hide _Publish_ if there is no source document
- Preview:
   - Hide _Reload_ if there is no source document
   - Show _Delete_ if there is no source document: deletes the resource from both preview and live buckets, then redirects to the homepage
   - Show _Unpublish_ if the page is published: deletes the resource from the live bucket, no redirect
- Live/Production:
   - Show _Unpublish_ if the page is published (implicit on Live): deletes the resource from the live bucket, then redirects to the preview page

**Comment by rofe** [comment]
Note: Unpublish will currently only work _after_ the source document has been deleted.
